#!/bin/bash

# This script and the dotfile folders must be located here:
DOTS_DIR="$HOME/dots"

DOTS_FLAG=""
PKG_FLAG=""
FONT_FLAG=""

# Parse args
while getopts "fpd" flag; do
  case "${flag}" in
    d) DOTS_FLAG="true" ;;
    f) FONT_FLAG="true" ;;
    p) PKG_FLAG="true" ;;
  esac
done

# Print usage if no options given
if [ "$PKG_FLAG" == "" ] && [ "$DOTS_FLAG" == "" ] && [ "$FONT_FLAG" == "" ]; then
  echo "Usage: $ ./bootstrap -f(onts) -p(ackages) -d(otfiles)"
  echo "On new setup run with all options: $ sudo ./bootstrap -fpd"
fi

##
# Packages
##
if [ "$PKG_FLAG" == "true" ]; then
  sudo apt-get update -y
  sudo apt-get upgrade -y
  sudo apt install -y stow vim-gtk3 compton rofi tmux i3 rxvt-unicode-256color i3blocks chromium-browser feh evince nodejs npm hsetroot fonts-font-awesome zsh curl

  # oh-my-zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

  # i3-gaps
  # dependencies for ubuntu 16.10+
  sudo apt install libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf libxcb-xrm0 libxcb-xrm-dev automake

  cd "$HOME"
  mkdir git
  cd git
  git clone https://www.github.com/Airblader/i3 i3-gaps
  cd i3-gaps
  autoreconf --force --install
  rm -rf build/
  mkdir -p build && cd build/
  ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
  make
  sudo make install
fi

##
# Fonts
##
if [ "$FONT_FLAG" == "true" ]; then
  add_font() {
    # url is a link to a .zip file download with font files somewhere in it
    # (this was written with nerdfonts.com in mind)

    # download font files (we should already be in .fonts dir)
    wget "$1"

    # get zip filename and folder to extract to
    zip_file=$(echo "$1" | rev | cut -d "/" -f 1 | rev)
    folder_name=$(echo "$zip_file" | cut -d "." -f 1)

    # unzip font files
    unzip "$zip_file" -d "$folder_name"

    # clean up zip file
    rm "$zip_file" -f
  }

  # Go to user's fonts directory
  mkdir $HOME/.fonts -p
  cd $HOME/.fonts

  # Fonts to grab
  add_font "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/ProggyClean.zip"
  add_font "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Mononoki.zip"
  add_font "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/FiraCode.zip"
  #add_font "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Noto.zip"

  # Update font cache
  fc-cache -fv
fi

##
# Dotfiles
##
if [ "$DOTS_FLAG" == "true" ]; then
  dotfile_dirs=$(ls $DOTS_DIR)

  # Remove common pre-existing dotfiles before stowing, if they exist
  [ -f "$HOME/.bashrc" ] && mv "$HOME/.bashrc" "$HOME/.bashrc.old"
  [ -f "$HOME/.xinitrc" ] && mv "$HOME/.xinitrc" "$HOME/.xinitrc.old"
  [ -f "$HOME/.Xresources" ] && mv "$HOME/.Xresources" "$HOME/.Xresources.old"
  [ -f "$HOME/.zshrc" ] && mv "$HOME/.zshrc" "$HOME/.zshrc.old"

  # Stow
  for dir in $dotfile_dirs; do
    if [ "$dir" != "bootstrap" ]; then # skip this file
      stow $dir
    fi
  done

  # Set background
  hsetroot -solid "#282828"

  # Apply Xresources
  xrdb -merge ~/.Xresources
fi
