#!/bin/bash

DOTS_DIR="$HOME/dots" # this script must be located here
DOTFILE_DIRS=$(ls $DOTS_DIR)

PKG_FLAG=""

# Parse args
while getopts "fp" flag; do
  case "${flag}" in
    p) PKG_FLAG="true" ;;
  esac
done

# Packages
if [ "$PKG_FLAG" == "true" ]; then
  sudo apt-get update
  sudo apt-get upgrade
  sudo apt install -y stow vim compton rofi tmux i3 rxvt-unicode-256color i3blocks chromium-browser feh evince nodejs npm hsetroot
fi

# Dotfiles
# Remove common pre-existing dotfiles before stowing
rm "$HOME/.bashrc" -f
rm "$HOME/.xinitrc" -f
rm "$HOME/.Xresources" -f

# Stow
for dir in $DOTFILE_DIRS; do
  if [ "$dir" != "bootstrap" ]; then # skip this file
    stow $dir
  fi
done

hsetroot -solid "#282828"

xrdb -merge ~/.Xresources
