#!/bin/bash

icon="$HOME/.i3/lock-icon.png"
scrot="/tmp/scrot.png"

(( $# )) && { icon=$1; }

scrot "$scrot"
convert "$scrot" -scale 10% -scale 1000% "$scrot"
convert "$scrot" "$icon" -gravity center -composite -matte "$scrot"
i3lock -u -i "$scrot"
