#!/bin/bash

STEP=5

case $BLOCK_BUTTON in
  # reversed to make natural scrolling feel natural in this context
  5) xbacklight -inc $STEP ;; # scroll down, increase
  4) xbacklight -dec $STEP ;; # scroll up, decrease
esac

printf '%.*f%%\n' 0 $(xbacklight -get)
