#!/bin/bash

STEP="1%"

case $BLOCK_BUTTON in
  3) amixer -q -D pulse sset Master 0% ;;  # right click, "mute" (set to 0%)
  # reversed to make natural scrolling feel natural in this context
  5) amixer -q -D pulse sset Master ${STEP}+ unmute ;; # scroll down, increase
  4) amixer -q -D pulse sset Master ${STEP}- unmute ;; # scroll up, decrease
esac

amixer -D pulse get 'Master' | cut -d "[" -f2 | cut -d "]" -f1 | tail -1
