#!/bin/bash

STEP="5%"

volume() {
  amixer -D pulse get 'Master' | cut -d "[" -f2 | cut -d "]" -f1 | tail -1
}

case $BLOCK_BUTTON in
  3) amixer -q -D pulse sset Master 0% ;;  # right click, "mute" (set to 0%)
  4) amixer -q -D pulse sset Master ${STEP}+ unmute ;; # scroll up, increase
  5) amixer -q -D pulse sset Master ${STEP}- unmute ;; # scroll down, decrease
esac

volume
